on:
  workflow_dispatch:
  pull_request:
    paths-ignore:
      - '.github/**'
      - 'docs/**'
      - 'README.md'

name: Build and Test

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: Cargo Build

    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6
        with:
          submodules: recursive

      - name: Setup Rust Toolchain
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          cache-workspaces: .
          cache-directories: ./target

      - name: Run cargo build
        run: cargo build

  test:
    name: Unit Tests

    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6
        with:
          submodules: recursive

      - name: Setup Rust Toolchain
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          cache-workspaces: .
          cache-directories: ./target

      - name: Run unit tests
        run: cargo test

  integration-test:
    name: Integration Tests (DAG)

    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6
        with:
          submodules: recursive

      - name: Setup Rust Toolchain
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          cache-workspaces: .
          cache-directories: ./target

      - name: Clone test repos
        run: |
          mkdir -p /tmp/buckal-test
          git clone --depth 1 https://github.com/yueneiqi/first-party-demo.git /tmp/buckal-test/first-party-demo
          git clone --depth 1 https://github.com/yueneiqi/monorepo-demo.git /tmp/buckal-test/monorepo-demo
          git clone --depth 1 https://github.com/sharkdp/fd.git /tmp/buckal-test/fd

      - name: Run integration tests
        run: cargo test --features integration-tests
